# Generated by Django 5.1.7 on 2025-03-17 20:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre_evenement', models.CharField(max_length=125)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('date_evenement', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('auteur', 'auteur'), ('lecteur', 'lecteur')], default='lecteur', max_length=120)),
                ('annee_experience', models.CharField(blank=True, choices=[('0-2 ans', '0-2 ans'), ('3-5 ans', '3-5 ans'), ('5-10 ans', '5-10 ans'), ('plus de 10 ans', 'plus de 10 ans')], max_length=120, null=True)),
                ('bio', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profil_picture', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('token', models.CharField(max_length=120)),
                ('pays', models.CharField(choices=[('DZ', 'Algérie'), ('AO', 'Angola'), ('BJ', 'Bénin'), ('BW', 'Botswana'), ('BF', 'Burkina Faso'), ('BI', 'Burundi'), ('CM', 'Cameroun'), ('CV', 'Cap-Vert'), ('CF', 'République Centrafricaine'), ('TD', 'Tchad'), ('KM', 'Comores'), ('CG', 'Congo-Brazzaville'), ('CD', 'Congo-Kinshasa'), ('DJ', 'Djibouti'), ('EG', 'Égypte'), ('GQ', 'Guinée Équatoriale'), ('ER', 'Érythrée'), ('SZ', 'Eswatini'), ('ET', 'Éthiopie'), ('GA', 'Gabon'), ('GM', 'Gambie'), ('GH', 'Ghana'), ('GN', 'Guinée'), ('GW', 'Guinée-Bissau'), ('CI', "Côte d'Ivoire"), ('KE', 'Kenya'), ('LS', 'Lesotho'), ('LR', 'Libéria'), ('LY', 'Libye'), ('MG', 'Madagascar'), ('MW', 'Malawi'), ('ML', 'Mali'), ('MR', 'Mauritanie'), ('MU', 'Maurice'), ('MA', 'Maroc'), ('MZ', 'Mozambique'), ('NA', 'Namibie'), ('NE', 'Niger'), ('NG', 'Nigéria'), ('RW', 'Rwanda'), ('ST', 'Sao Tomé-et-Principe'), ('SN', 'Sénégal'), ('SC', 'Seychelles'), ('SL', 'Sierra Leone'), ('SO', 'Somalie'), ('ZA', 'Afrique du Sud'), ('SS', 'Soudan du Sud'), ('SD', 'Soudan'), ('TZ', 'Tanzanie'), ('TG', 'Togo'), ('TN', 'Tunisie'), ('UG', 'Ouganda'), ('ZM', 'Zambie'), ('ZW', 'Zimbabwe')], default='CM', max_length=100, null=True)),
                ('valid_auteur', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('valid', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Social_link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
